### PR TITLE
Miscellaneous changes

### PR DESCRIPTION
**Pull request by pendingchaos**
Not too certain about the device recreation change. It can fix issues where the replay tool is given multiple databases and ends up requesting too old of a Vulkan version for one of them. I split the commit into two to make review easier.

### CODE REVIEW

**Comment by pendingchaos** [comment]
I've created a separate PR for the validation checker fixes: https://github.com/ValveSoftware/Fossilize/pull/66

When running the replay tool with several databases (Sascha Willems demos and pipelines from vkpipeline-db's runner), it seems it would end up using the vulkan version of one the Sascha Willems demos (Vulkan 1.0) but some of the vkpipeline-db pipelines require Vulkan 1.1

It's not a real issue at the moment, since statistics from Sascha Willems demos aren't too interesting. If it every becomes a real issue, I think it should be possible to run the replay tool once for each application instead of all at once

**Comment by HansKristian-Work** [comment]
Is this happening when using the "combined" multi-archive support of fossilize-replay?

**Comment by pendingchaos** [comment]
> Is this happening when using the "combined" multi-archive support of fossilize-replay?

I pass several databases to fossilize-replay (like `./fossilize-replay --enable-pipeline-stats output.csv sascha-willems/bloom.foz rottr.foz ...`). If that's what it's called, then yes

**Comment by HansKristian-Work** [comment]
Right, that approach is somewhat fiddly w.r.t. application infos. The recommended approach is to replay different foz archives separately in different processes for this case, but one thing we can add to Fossilize is to look at all application infos first, and then select which one we should be using based on things like Vulkan version or other user-defined filters.

**Comment by pendingchaos** [comment]
> Right, that approach is somewhat fiddly w.r.t. application infos. The recommended approach is to replay different foz archives separately in different processes for this case, but one thing we can add to Fossilize is to look at all application infos first, and then select which one we should be using based on things like Vulkan version or other user-defined filters.

It shouldn't be too difficult to update the replay script I'm using to run fossilize-replay for each application and concatenate the CSVs. Since that's the recommended approach, I think I'll do that

Should I close this PR?

**Comment by HansKristian-Work** [comment]
Sorry for late reply. Yes, I think this can be closed. The appinfo selection should be solved, but in a very different way. I'll look into that eventually.

**Pull request closed without merging**
